name: Run Cypress Tests
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install
        run: npm ci

      - name: Cypress Tests
        run: npx start-server-and-test 'npm start' http://localhost:3000 'npx cypress run'
