name: Run Cypress Tests
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          browser: chrome
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180
